### ISSUE TITLE
Infinite recursion between Game.run() and MainMenu.run()

### ISSUE THREAD

**Issue by larsbutler** [sloukit/pydew-valley-uzh#14]
I noticed that when you transition between `Game` and `Main Menu`, the run() methods of each class call each, growing the call stack, creating more object (growing memory), and never letting the unused objects be garbage collected. With enough repetitions, this is going to cause a stack overflow or out of memory error (memory leak).

Relevant code: https://github.com/sloukit/pydew-valley-uzh/blob/1785878e71e97ae08a7dd11273e6a8e36fe0ee6a/main.py

This looks like a better model for transitioning between menu and game states: https://www.youtube.com/watch?v=b_DkQrJxpck. That's just what I could find after some quick research.

Edit: Another option would be https://www.youtube.com/watch?v=r0ixaTQxsUI.

**Comment by fortwoone** [comment]
Good one. Besides, I don’t know exactly why MainMenu calls game again if run from Game

**Comment by ultimateownsz** [comment]
Using lists for the different states looks like an good method to switch the states of the game.

**Comment by SSnowly** [comment]
Fixed in next update for mainmenu.

**Comment by SSnowly** [comment]
Fixed in #16

**Comment by larsbutler** [comment]
There's still an issue, causing a game crash:

```
Traceback (most recent call last):
  File "/path/to/pydew-valley-uzh/main.py", line 141, in <module>
    game = MainMenu()
           ^^^^^^^^^^
  File "/path/to/pydew-valley-uzh/main.py", line 115, in __init__
    self.game = Game(self)
                ^^^^^^^^^^
TypeError: Game.__init__() takes 1 positional argument but 2 were given
```

I'm not sure what the intention was here with passing `self` to the Game() constructor; maybe to share state was the idea?

**Comment by fortwoone** [comment]
PR #29 has fixed this, and it has been merged
